baseURL = "https://hugo-architect-theme-demo.netlify.com/"
title = "Architect theme"
theme = "hugo-architect-theme"
pygmentsCodeFences = "true"
pygmentsUseClasses = "true"

[params]
 use_sass = "false"
 show_downloads = "true"
 description = "Architect is a Jekyll theme ported to Hugo."
 gh_repo_owner = "hawkeye116477"
 gh_repo_name = "hugo-architect-theme"

 [params.webmaster_verifications]
  bing = ""
  google = ""
  alexa = ""
  yandex = ""
  baidu = ""
